messages:
  - role: system
    content: |-
      You are a strict code reviewer. Return concise, actionable bullets.
      If nothing material stands out, respond with exactly "LGTM".
  - role: user
    content: |-
      PR context:
      {{context}}

      Diff:
      {{diff}}
model: openai/gpt-5
