name: AI PR review
on:
  pull_request: { types: [opened, synchronize, reopened] }
permissions:
  contents: read
  pull-requests: write
  models: read
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Collect diff (patches)
        id: diff
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            const run = require('./.github/scripts/collect-pr-context.js');
            await run({ github, context, core });
      - name: Review with a model
        id: ai
        uses: actions/ai-inference@v1
        with:
          prompt-file: ./.github/prompts/ai-code-review.prompt.yml
          input: |
            context: ${{ toJson(steps.diff.outputs.context) }}
            diff: ${{ toJson(steps.diff.outputs.diff) }}
      - name: Comment on PR
        uses: actions/github-script@v8
        with:
          script: |
            const body = ${{ toJson(steps.ai.outputs.response) }};
            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
